before_install:
  - chmod +x gradlew

language: java
jdk:
  - openjdk8
branches:
  only:
    - master
#Travis CI Server Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

#CI finish send to email
notifications:
  email:
    recipients:
      - amsmdmfm159@naver.com